POST http://127.0.0.1:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2MTg2ZjZjY2UyYTY5MDAyMzJiNjIyOTAiLCJpYXQiOjE2MzYyMzQ5NjgsImV4cCI6MTYzNjIzODU2OH0.YS3WdpaJCzmnFupYncUp7_c93wuIYvEw7AUqTb_IGeQ

{
    "title": "new blog3",
    "author": "John Doe2",
    "url": "www.example.com",
    "likes": 20
}