
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description":"TestDesc",
    "specialist":"TestSpecialist",
    "date":"2000-12-12",
    "type": "HealthCheck",
    "healthCheckRating": 0,
    "diagnosisCodes": [
        "LH23.3",
        "KL435.3"
    ]
}